const data=[
 {code:"TRM-2026-00124",student:"María Quispe Mamani",type:"Certificado de estudios",date:"02/10/2026",status:"En proceso"},
 {code:"TRM-2026-00123",student:"José Apaza Condori",type:"Constancia de estudios",date:"01/10/2026",status:"Por hacer"},
 {code:"TRM-2026-00122",student:"Rosa Choque Huanca",type:"Récord académico",date:"30/09/2026",status:"En revisión"},
 {code:"TRM-2026-00121",student:"Luis Mamani Paredes",type:"Duplicado de documento",date:"29/09/2026",status:"Finalizado"},
 {code:"TRM-2026-00120",student:"Ana Flores Yana",type:"Convalidación",date:"28/09/2026",status:"Finalizado"}
];
const navTitles={dashboard:"Panel de Secretaría Académica",nuevo:"Registrar nuevo trámite",seguimiento:"Seguimiento del trámite",tramites:"Trámites registrados",reportes:"Reportes e indicadores"};
function showView(id){document.querySelectorAll(".view").forEach(v=>v.classList.remove("active-view"));document.getElementById(id).classList.add("active-view");document.querySelectorAll(".nav-item").forEach(b=>b.classList.toggle("active",b.dataset.view===id));document.getElementById("page-title").textContent=navTitles[id];if(id==="tramites")renderTable();if(id==="dashboard")renderRecent();window.scrollTo({top:0,behavior:"smooth"})}
document.querySelectorAll(".nav-item").forEach(b=>b.addEventListener("click",()=>showView(b.dataset.view)));
function badge(s){let c=s==="Finalizado"?"done":s==="En proceso"?"process":s==="En revisión"?"review":"pending";return `<span class="badge ${c}">${s}</span>`}
function renderRecent(){document.getElementById("recent-list").innerHTML=data.slice(0,4).map(x=>`<div class="recent"><div><b>${x.code}</b><span>${x.student} · ${x.type}</span></div>${badge(x.status)}</div>`).join("")}
function renderTable(){let q=document.getElementById("filter").value.toLowerCase(),s=document.getElementById("statusFilter").value;let rows=data.filter(x=>(!q||`${x.code} ${x.student} ${x.type}`.toLowerCase().includes(q))&&(!s||x.status===s));document.getElementById("table-body").innerHTML=rows.map(x=>`<tr><td><strong>${x.code}</strong></td><td>${x.student}</td><td>${x.type}</td><td>${x.date}</td><td>${badge(x.status)}</td><td><button class="action" onclick="trackCode('${x.code}')">Ver seguimiento</button></td></tr>`).join("")||`<tr><td colspan="6">No se encontraron trámites.</td></tr>`}
function trackCode(code){showView("seguimiento");document.getElementById("search-code").value=code;track()}
function track(){let code=document.getElementById("search-code").value.trim().toUpperCase();let x=data.find(a=>a.code===code);let box=document.getElementById("tracking-result");box.classList.remove("hidden");if(!x){box.innerHTML=`<div class="panel tracking-card"><b>No se encontró la solicitud.</b><p style="color:#667085;font-size:12px">Verifique el código e inténtelo nuevamente.</p></div>`;return}let active=x.status==="Finalizado"?4:x.status==="En revisión"?3:x.status==="En proceso"?2:1;let labels=["Recepción","Revisión","Atención","Entrega"];box.innerHTML=`<div class="panel tracking-card"><div class="panel-head"><div><h3>${x.code}</h3><span>${x.student} · ${x.type}</span></div>${badge(x.status)}</div><div class="timeline">${labels.map((l,i)=>`<div class="step ${i<active?"done":""}"><div class="circle">${i<active?"✓":i+1}</div><span>${l}</span></div>`).join("")}</div><p style="margin-top:25px;font-size:12px;color:#667085">Última actualización: ${x.date}. El estado mostrado corresponde al seguimiento registrado en el sistema.</p></div>`}
document.getElementById("form-tramite").addEventListener("submit",e=>{e.preventDefault();let code=`TRM-2026-${String(125+data.length).padStart(5,"0")}`;data.unshift({code,student:student.value,type:type.value,date:"02/10/2026",status:"Por hacer"});document.getElementById("success").classList.remove("hidden");document.getElementById("success").innerHTML=`<b>Solicitud registrada correctamente.</b><br>Código de seguimiento: <strong>${code}</strong>`;e.target.reset();renderRecent();document.getElementById("m-total").textContent=24+data.length-5;});
renderRecent();renderTable();
